SELECT DATABASE_NAME,SERVICE_NAME, PORT,SQL_PORT,(PORT + 2) HTTP_PORT 
FROM SYS_DATABASES.M_SERVICES 
where ((SERVICE_NAME='indexserver' and COORDINATOR_TYPE= 'MASTER') or (SERVICE_NAME='xsengine'));
